credentials:
  usernames:
    CICC-Software:
      email: CICC-Software
      name: CICC-Software
      password: $2b$12$WC0Ctz595I5zGZ2ZnDWwou2wx89VRAgdSkksz98I0u.YLjKj.k/pa
cookie:
  expiry_days: 1
  key: $2b$12$EdQwT9uexP3qACIvKeTuqeJvRyMkrRXyujoF59Tec3zpdfL/za1ge
  name: cicc-hanrui-chatgpt-summary
preauthorized:
  emails:
  - rachelruihan@outlook.com
